PROJ_NAME=draw
DEBUG=yes
BENCH=no
MULDIV=no


SRCS = 	$(wildcard src/*.c) \
	$(wildcard src/*.cpp)  \
	$(wildcard src/*.S)


LDSCRIPT = ../common/linker.ld

include ../common/gcc.mk
include ../common/subproject.mk


			
